ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN_TNV';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN_YCCT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN_KHO';
