ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'DA_TIEP_NHAN' AFTER 'CHO_TIEP_NHAN';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'DANG_TUYEN' AFTER 'DA_TIEP_NHAN';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'DA_DU_DOI' AFTER 'DANG_TUYEN';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'DANG_THUC_HIEN' AFTER 'DA_DU_DOI';
